version: "3.7"

services: 
  django:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./django
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on: 
      - django

volumes:
  static: